import type { Metadata } from "next";

import "webflow/css/normalize.css";
import "webflow/css/tags.css";
import "webflow/css/variables.css";
import "webflow/css/defaults.css";
import "webflow/css/classes.css";
import "./globals.css";
//import "webflow/css/global.css";
import { DevLinkProvider } from "webflow/DevLinkProvider";
import { DevLinkFontTags } from "webflow/webflow_modules/DevLinkFontTags";

export const metadata: Metadata = {
  title: "Webflow Cloud Next.js App",
  description: "Generated by Webflow Cloud",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <DevLinkFontTags />
      </head>
      <body className="body-global">
        {" "}
        <DevLinkProvider>{children}</DevLinkProvider>
      </body>
    </html>
  );
}
