/**
 * @generated
 * @file CardGridBlock (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "../devlinkScope";
import Block from "../webflow_modules/Basic/components/Block";
import Heading from "../webflow_modules/Basic/components/Heading";
import Image from "../webflow_modules/Basic/components/Image";
import Paragraph from "../webflow_modules/Basic/components/Paragraph";

/**
 * Props for {@link CardGridBlock}
 */
export type CardGridBlockProps = {
  body?: React.ReactNode;
  gvcImage?: string;
  heading?: React.ReactNode;
};

/**
 * CardGridBlock
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function CardGridBlock({
  body = "Organise your spending your way. Create different cards for subscriptions, travel, ads, or everyday payments — each with its own limits and settings.",
  gvcImage = "",
  heading = "Heading",
}: CardGridBlockProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"gvcitemwrapper"}
        id={"w-node-_13f5c36b-e55c-e9a2-9600-773b75372e14-75372e14"}
        tag={"div"}
      >
        <Block className={"gvcimageframe is-out"} tag={"div"}>
          <Block className={"gvcimageframe is-in"} tag={"div"}>
            <Image
              alt={""}
              className={"gvcimage"}
              height={"792"}
              loading={"lazy"}
              src={gvcImage}
              width={"1164"}
            />
          </Block>
        </Block>
        <Block className={"gvccopy"} tag={"div"}>
          <Heading className={"gvcheading"} tag={"h3"}>
            {heading}
          </Heading>
          <Paragraph className={"gvcbody"}>{body}</Paragraph>
        </Block>
      </Block>
    </div>
  );
}
