/**
 * @generated
 * @file CommunityBenefits (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Image from "./webflow_modules/Basic/components/Image";

/**
 * Props for {@link CommunityBenefits}
 */
export type CommunityBenefitsProps = {
  body?: React.ReactNode;
  heading?: React.ReactNode;
  icon?: string;
  variant?: "Base" | "Var 2" | "Var 3" | "Var 4" | "Var 5" | "Var 6";
};

/**
 * CommunityBenefits
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function CommunityBenefits({
  body = "Meet and build connections with people in your industry. Get inspired by bouncing ideas off each other and sharing experiences",
  heading = "Connect with freelancers and digital nomads around the world",
  icon = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/65aca0532f963c198aee0aa1_icon%20main.svg",
  variant = "Base",
}: CommunityBenefitsProps) {
  const _styleVariantMap = {
    Base: "",
    "Var 2": "w-variant-895a3a18-ad40-3c7b-5d71-1ea697930a41",
    "Var 3": "w-variant-e547df06-9806-bf57-e738-697e7f733f6b",
    "Var 4": "w-variant-5bb87c38-ba15-35e4-d06d-7a587623d399",
    "Var 5": "w-variant-e3aff9a6-f960-3e43-9aef-4d29c051bb2d",
    "Var 6": "w-variant-d3deffd2-4730-9a48-7b03-9ec856b834c8",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={`community_vp ${_activeStyleVariant}`}
        id={"w-node-ccf2936b-c83f-dcfd-1b94-c83f477278fb-477278fb"}
        tag={"div"}
      >
        <Image
          alt={""}
          className={`image-99 ${_activeStyleVariant}`}
          height={"72"}
          loading={"lazy"}
          src={icon}
          width={"72"}
        />
        <Block className={`text-block-67 ${_activeStyleVariant}`} tag={"div"}>
          {heading}
        </Block>
        <Block className={`text-block-68 ${_activeStyleVariant}`} tag={"div"}>
          {body}
        </Block>
      </Block>
    </div>
  );
}
