/**
 * @generated
 * @file CompareTableMobile (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Image from "./webflow_modules/Basic/components/Image";

/**
 * Props for {@link CompareTableMobile}
 */
export type CompareTableMobileProps = {
  compLogo?: string;
  feat01?: React.ReactNode;
  feat02?: React.ReactNode;
  feat03?: React.ReactNode;
  feat04?: React.ReactNode;
  feat05?: React.ReactNode;
  feat07?: React.ReactNode;
  status01?: string;
  status02?: string;
  status03?: string;
  status04?: string;
  status05?: string;
  status06?: string;
  status07?: string;
  text?: React.ReactNode;
};

/**
 * CompareTableMobile
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function CompareTableMobile({
  compLogo = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/68d42778ab5ba7ec94480081_3e6c7b26a9db3a34988ad09f173a40aa_GreyBusiness-lockup-dark.svg",
  feat01 = "Multi-currency accounts",
  feat02 = "Multi-currency accounts",
  feat03 = "Multi-currency accounts",
  feat04 = "Multi-currency accounts",
  feat05 = "Multi-currency accounts",
  feat07 = "Multi-currency accounts",
  status01 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/68d3ee2140be81e47f4cdf33_yes.svg",
  status02 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/68d3ee2140be81e47f4cdf33_yes.svg",
  status03 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/68d3ee2140be81e47f4cdf33_yes.svg",
  status04 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/68d3ee2140be81e47f4cdf33_yes.svg",
  status05 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/68d3ee2140be81e47f4cdf33_yes.svg",
  status06 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/68d3ee2140be81e47f4cdf33_yes.svg",
  status07 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/68d3ee2140be81e47f4cdf33_yes.svg",
  text = "Multi-currency accounts",
}: CompareTableMobileProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block
        className={"bb-features-wrapper"}
        id={"w-node-_9d286380-94fb-e4ec-c8ea-8d18eedccf6a-eedccf6a"}
        tag={"div"}
      >
        <Block
          className={"compare-logo-wrapper"}
          id={"w-node-_9d286380-94fb-e4ec-c8ea-8d18eedccf6b-eedccf6a"}
          tag={"div"}
        >
          <Image
            alt={""}
            className={"compare-logo"}
            height={"auto"}
            loading={"lazy"}
            src={compLogo}
            width={"auto"}
          />
        </Block>
        <Block
          className={"compare-copy-wrapper"}
          id={"w-node-_9d286380-94fb-e4ec-c8ea-8d18eedccf6d-eedccf6a"}
          tag={"div"}
        >
          <Block
            className={"compare-icon-wrapper"}
            id={"w-node-_9d286380-94fb-e4ec-c8ea-8d18eedccf6e-eedccf6a"}
            tag={"div"}
          >
            <Image
              alt={""}
              className={"comapre-icon"}
              height={"auto"}
              loading={"lazy"}
              src={status01}
              width={"auto"}
            />
          </Block>
          <Block className={"compare-copy"} tag={"div"}>
            {feat01}
          </Block>
        </Block>
        <Block
          className={"compare-copy-wrapper"}
          id={"w-node-_9d286380-94fb-e4ec-c8ea-8d18eedccf72-eedccf6a"}
          tag={"div"}
        >
          <Block
            className={"compare-icon-wrapper"}
            id={"w-node-_9d286380-94fb-e4ec-c8ea-8d18eedccf73-eedccf6a"}
            tag={"div"}
          >
            <Image
              alt={""}
              className={"comapre-icon"}
              height={"auto"}
              loading={"lazy"}
              src={status02}
              width={"auto"}
            />
          </Block>
          <Block className={"compare-copy"} tag={"div"}>
            {feat02}
          </Block>
        </Block>
        <Block
          className={"compare-copy-wrapper"}
          id={"w-node-_9d286380-94fb-e4ec-c8ea-8d18eedccf77-eedccf6a"}
          tag={"div"}
        >
          <Block
            className={"compare-icon-wrapper"}
            id={"w-node-_9d286380-94fb-e4ec-c8ea-8d18eedccf78-eedccf6a"}
            tag={"div"}
          >
            <Image
              alt={""}
              className={"comapre-icon"}
              height={"auto"}
              loading={"lazy"}
              src={status03}
              width={"auto"}
            />
          </Block>
          <Block className={"compare-copy"} tag={"div"}>
            {feat03}
          </Block>
        </Block>
        <Block
          className={"compare-copy-wrapper"}
          id={"w-node-_9d286380-94fb-e4ec-c8ea-8d18eedccf7c-eedccf6a"}
          tag={"div"}
        >
          <Block
            className={"compare-icon-wrapper"}
            id={"w-node-_9d286380-94fb-e4ec-c8ea-8d18eedccf7d-eedccf6a"}
            tag={"div"}
          >
            <Image
              alt={""}
              className={"comapre-icon"}
              height={"auto"}
              loading={"lazy"}
              src={status04}
              width={"auto"}
            />
          </Block>
          <Block className={"compare-copy"} tag={"div"}>
            {feat04}
          </Block>
        </Block>
        <Block
          className={"compare-copy-wrapper"}
          id={"w-node-_9d286380-94fb-e4ec-c8ea-8d18eedccf81-eedccf6a"}
          tag={"div"}
        >
          <Block
            className={"compare-icon-wrapper"}
            id={"w-node-_9d286380-94fb-e4ec-c8ea-8d18eedccf82-eedccf6a"}
            tag={"div"}
          >
            <Image
              alt={""}
              className={"comapre-icon"}
              height={"auto"}
              loading={"lazy"}
              src={status05}
              width={"auto"}
            />
          </Block>
          <Block className={"compare-copy"} tag={"div"}>
            {feat05}
          </Block>
        </Block>
        <Block
          className={"compare-copy-wrapper"}
          id={"w-node-_9d286380-94fb-e4ec-c8ea-8d18eedccf86-eedccf6a"}
          tag={"div"}
        >
          <Block
            className={"compare-icon-wrapper"}
            id={"w-node-_9d286380-94fb-e4ec-c8ea-8d18eedccf87-eedccf6a"}
            tag={"div"}
          >
            <Image
              alt={""}
              className={"comapre-icon"}
              height={"auto"}
              loading={"lazy"}
              src={status06}
              width={"auto"}
            />
          </Block>
          <Block className={"compare-copy"} tag={"div"}>
            {feat07}
          </Block>
        </Block>
        <Block
          className={"compare-copy-wrapper"}
          id={"w-node-_9d286380-94fb-e4ec-c8ea-8d18eedccf8b-eedccf6a"}
          tag={"div"}
        >
          <Block
            className={"compare-icon-wrapper"}
            id={"w-node-_9d286380-94fb-e4ec-c8ea-8d18eedccf8c-eedccf6a"}
            tag={"div"}
          >
            <Image
              alt={""}
              className={"comapre-icon"}
              height={"auto"}
              loading={"lazy"}
              src={status07}
              width={"auto"}
            />
          </Block>
          <Block className={"compare-copy"} tag={"div"}>
            {text}
          </Block>
        </Block>
      </Block>
    </div>
  );
}
