/**
 * @generated
 * @file CompareTable (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Image from "./webflow_modules/Basic/components/Image";

/**
 * Props for {@link CompareTable}
 */
export type CompareTableProps = {
  greyStatus?: string;
  mercuryStatus?: string;
  payoneerStatus?: string;
  revolutStatus?: string;
  title?: React.ReactNode;
  wiseStatus?: string;
};

/**
 * CompareTable
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function CompareTable({
  greyStatus = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/68d3ee2140be81e47f4cdf33_yes.svg",
  mercuryStatus = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/68d3ee2140be81e47f4cdf33_yes.svg",
  payoneerStatus = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/68d3ee2140be81e47f4cdf33_yes.svg",
  revolutStatus = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/68d3ee2140be81e47f4cdf33_yes.svg",
  title = "Multi-currency accounts",
  wiseStatus = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/68d3ee2140be81e47f4cdf33_yes.svg",
}: CompareTableProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"compare"} tag={"div"}>
        <Block
          className={"compare-copy-wrapper"}
          id={"w-node-_55a96249-50dc-02ca-e00c-ff6521c81205-21c81204"}
          tag={"div"}
        >
          <Block className={"compare-copy"} tag={"div"}>
            {title}
          </Block>
        </Block>
        <Block
          className={"compare-icon-wrapper"}
          id={"w-node-_55a96249-50dc-02ca-e00c-ff6521c81208-21c81204"}
          tag={"div"}
        >
          <Image
            alt={""}
            className={"comapre-icon"}
            height={"auto"}
            loading={"lazy"}
            src={greyStatus}
            width={"auto"}
          />
        </Block>
        <Block
          className={"compare-icon-wrapper"}
          id={"w-node-_55a96249-50dc-02ca-e00c-ff6521c8120a-21c81204"}
          tag={"div"}
        >
          <Image
            alt={""}
            className={"comapre-icon"}
            height={"auto"}
            loading={"lazy"}
            src={mercuryStatus}
            width={"auto"}
          />
        </Block>
        <Block
          className={"compare-icon-wrapper"}
          id={"w-node-_55a96249-50dc-02ca-e00c-ff6521c8120c-21c81204"}
          tag={"div"}
        >
          <Image
            alt={""}
            className={"comapre-icon"}
            height={"auto"}
            loading={"lazy"}
            src={payoneerStatus}
            width={"auto"}
          />
        </Block>
        <Block
          className={"compare-icon-wrapper"}
          id={"w-node-_55a96249-50dc-02ca-e00c-ff6521c8120e-21c81204"}
          tag={"div"}
        >
          <Image
            alt={""}
            className={"comapre-icon"}
            height={"auto"}
            loading={"lazy"}
            src={wiseStatus}
            width={"auto"}
          />
        </Block>
        <Block
          className={"compare-icon-wrapper"}
          id={"w-node-_55a96249-50dc-02ca-e00c-ff6521c81210-21c81204"}
          tag={"div"}
        >
          <Image
            alt={""}
            className={"comapre-icon"}
            height={"auto"}
            loading={"lazy"}
            src={revolutStatus}
            width={"auto"}
          />
        </Block>
      </Block>
    </div>
  );
}
