/**
 * @generated
 * @file CookieConsent (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Link from "./webflow_modules/Basic/components/Link";

/**
 * Props for {@link CookieConsent}
 */
export type CookieConsentProps = {};

/**
 * CookieConsent
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function CookieConsent({}: CookieConsentProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"cookiecontainer"} tag={"div"}>
        <Block className={"cookiewrapper"} fs-cc={"banner"} tag={"div"}>
          <Block className={"cookiecopywrapper"} tag={"div"}>
            <Block className={"cookiecopy"} tag={"div"}>
              {
                "Grey uses cookies to improve your website experience. By enabling cookies, you help understand your usage, tailor marketing efforts and enhance navigation. Please view our "
              }
              <Link
                button={false}
                options={{
                  href: "http://grey.co/legal/privacy-policy",
                  target: "_blank",
                }}
              >
                {"Privacy Policy"}
              </Link>
              {" for more information"}
            </Block>
          </Block>
          <Block className={"cookiebuttons"} tag={"div"}>
            <Link
              button={true}
              className={"cookie pref"}
              fs-cc={"open-preferences"}
              options={{
                href: "#",
              }}
            >
              {"Preferences"}
            </Link>
            <Link
              button={true}
              className={"cookie deny"}
              fs-cc={"deny"}
              options={{
                href: "#",
              }}
            >
              {"Decline all"}
            </Link>
            <Link
              button={true}
              className={"cookie accept"}
              fs-cc={"allow"}
              options={{
                href: "#",
              }}
            >
              {"Accept all"}
            </Link>
          </Block>
        </Block>
      </Block>
    </div>
  );
}
