/**
 * @generated
 * @file CsrSection (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import BlockContainer from "./webflow_modules/Layout/components/BlockContainer";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link CsrSection}
 *
 * Drag and drop as a full section
 */
export type CsrSectionProps = {
  supportingImage?: string;
  text?: React.ReactNode;
  title?: React.ReactNode;
  variant?: "Base" | "Dark" | "Blue";
  visibility?: boolean;
};

/**
 * CsrSection
 *
 * Drag and drop as a full section
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function CsrSection({
  supportingImage = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6563c15e45db91a91be0605b_csr%20image.webp",
  text = "At Grey, we believe in giving back and supporting meaningful causes. Through our dedicated social impact programs and corporate social responsibility initiatives, we strive to make a difference in the communities we serve. By choosing Grey, you’re not just simplifying your global transactions but contributing to a better world",
  title = (
    <>
      {"Making a"}
      <br />
      {"difference together"}
    </>
  ),
  variant = "Base",
  visibility = true,
}: CsrSectionProps) {
  const _styleVariantMap = {
    Base: "",
    Dark: "w-variant-a6a38bf0-efd6-a63f-5164-59ee2b769d45",
    Blue: "w-variant-44decba5-1db5-d36d-c08f-5e9449dccef5",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={`new-section _w-padding ${_activeStyleVariant}`}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <BlockContainer
          className={`new-section-container ${_activeStyleVariant}`}
          grid={{
            type: "container",
          }}
          tag={"div"}
        >
          <Block className={`csr ${_activeStyleVariant}`} tag={"div"}>
            <Block
              className={`csr-copy-wrapper ${_activeStyleVariant}`}
              tag={"div"}
            >
              {visibility ? (
                <Image
                  alt={
                    "Three pink and red gradient hearts of varying sizes overlapping on a transparent background."
                  }
                  className={`csr_icon ${_activeStyleVariant}`}
                  height={"Auto"}
                  loading={"lazy"}
                  src={
                    "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/67f3f13267934611287cde72_Heart.avif"
                  }
                  width={"323"}
                />
              ) : null}
              <Heading
                className={`new-section-h3 ${_activeStyleVariant}`}
                tag={"h2"}
              >
                {title}
              </Heading>
              <Block
                className={`new-subheading is-100 is-align-left ${_activeStyleVariant}`}
                tag={"div"}
              >
                {text}
              </Block>
            </Block>
            <Image
              alt={""}
              className={`csr-image ${_activeStyleVariant}`}
              height={"Auto"}
              loading={"lazy"}
              src={supportingImage}
              width={"1138"}
            />
          </Block>
        </BlockContainer>
      </Section>
    </div>
  );
}
