/**
 * @generated
 * @file FooterObsolete (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Container from "./webflow_modules/Layout/components/Container";
import Grid from "./webflow_modules/Layout/components/Grid";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";
import NotSupported from "./webflow_modules/Builtin/components/NotSupported";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link FooterObsolete}
 */
export type FooterObsoleteProps = {};

/**
 * FooterObsolete
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported element: `Collection List`
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function FooterObsolete({}: FooterObsoleteProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"wrapper footer"}
        grid={{
          type: "section",
        }}
        tag={"div"}
      >
        <Container className={"footer-wrapper max-width"} tag={"div"}>
          <Block className={"div-block-29"} tag={"div"}>
            <Heading className={"heading-2 footer"} tag={"h2"}>
              {"Sign up on Grey and start receiving foreign payments"}
            </Heading>
            <Link
              button={true}
              className={"button"}
              options={{
                href: "#",
                target: "_blank",
              }}
            >
              {"Get started — for free"}
            </Link>
          </Block>
          <Block className={"div-block-30"} tag={"div"}>
            <Grid className={"grid-4"} tag={"div"}>
              <Block
                className={"products-wrapper"}
                id={"w-node-e30a8f3f-ddd3-d6d4-7289-e108022dd1f8-022dd1ef"}
                tag={"div"}
              >
                <Heading className={"footer-heading"} tag={"h4"}>
                  {"Products"}
                </Heading>
                <NotSupported _atom={"Collection List"} />
              </Block>
              <Block
                className={"products-wrapper"}
                id={"w-node-_620ce92f-b21f-df24-b401-f5e33c3035af-022dd1ef"}
                tag={"div"}
              >
                <Heading className={"footer-heading"} tag={"h4"}>
                  {"Company"}
                </Heading>
                <Link
                  block={"inline"}
                  button={false}
                  className={"footer_text-wrapper"}
                  options={{
                    href: "/blog",
                    target: "_blank",
                  }}
                >
                  <Paragraph className={"footer-text"}>{"Blog"}</Paragraph>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"footer_text-wrapper"}
                  options={{
                    href: "/press-page",
                  }}
                >
                  <Paragraph className={"footer-text"}>
                    {"In the Press"}
                  </Paragraph>
                </Link>
                <Link
                  block={"inline"}
                  button={false}
                  className={"footer_text-wrapper"}
                  options={{
                    href: "https://grey.bamboohr.com/jobs",
                    target: "_blank",
                  }}
                >
                  <Paragraph className={"footer-text"}>{"Careers"}</Paragraph>
                </Link>
              </Block>
              <Block
                className={"products-wrapper"}
                id={"w-node-_03f0b0e2-2e0d-fc8f-4847-edb940061d32-022dd1ef"}
                tag={"div"}
              >
                <Heading className={"footer-heading"} tag={"h4"}>
                  {"Discover"}
                </Heading>
                <NotSupported _atom={"Collection List"} />
              </Block>
              <Block
                className={"products-wrapper"}
                id={"w-node-e30a8f3f-ddd3-d6d4-7289-e108022dd208-022dd1ef"}
                tag={"div"}
              >
                <Heading className={"footer-heading"} tag={"h4"}>
                  {"Legal"}
                </Heading>
                <NotSupported _atom={"Collection List"} />
              </Block>
              <Block
                className={"products-wrapper"}
                id={"w-node-e30a8f3f-ddd3-d6d4-7289-e108022dd201-022dd1ef"}
                tag={"div"}
              >
                <Heading className={"footer-heading"} tag={"h4"}>
                  {"Support"}
                </Heading>
                <Link
                  block={"inline"}
                  button={false}
                  className={"footer_text-wrapper"}
                  options={{
                    href: "https://support.grey.co/en/",
                    target: "_blank",
                  }}
                >
                  <Paragraph className={"footer-text"}>
                    {"Help Center"}
                  </Paragraph>
                </Link>
              </Block>
              <Block
                className={"products-wrapper contact"}
                id={"w-node-e30a8f3f-ddd3-d6d4-7289-e108022dd20f-022dd1ef"}
                tag={"div"}
              >
                <Paragraph className={"footer-text"}>{"Contact Us"}</Paragraph>
                <Paragraph className={"footer-text"}>
                  <Link
                    button={false}
                    className={"link"}
                    options={{
                      href: "#",
                    }}
                  >
                    {"hello@grey.co"}
                  </Link>
                </Paragraph>
                <Block className={"footer-social-block-three"} tag={"div"}>
                  <Link
                    block={"inline"}
                    button={false}
                    className={"footer-social-link-three"}
                    options={{
                      href: "https://twitter.com/greyfinance",
                      target: "_blank",
                    }}
                  >
                    <Image
                      alt={"Twitter"}
                      height={"auto"}
                      loading={"lazy"}
                      src={
                        "https://uploads-ssl.webflow.com/62434fa732124a0fb112aab4/62434fa732124ab37a12aaf0_twitter%20big.svg"
                      }
                      width={"auto"}
                    />
                  </Link>
                  <Link
                    block={"inline"}
                    button={false}
                    className={"footer-social-link-three"}
                    options={{
                      href: "https://instagram.com/greyfinance",
                    }}
                  >
                    <Image
                      alt={"Instagram"}
                      height={"auto"}
                      loading={"lazy"}
                      src={
                        "https://uploads-ssl.webflow.com/62434fa732124a0fb112aab4/62434fa732124a61f512aaed_instagram%20big.svg"
                      }
                      width={"auto"}
                    />
                  </Link>
                  <Link
                    block={"inline"}
                    button={false}
                    className={"footer-social-link-three"}
                    options={{
                      href: "https://www.youtube.com/channel/UCZE2POWPKgPks0bowGGbOZw/about",
                      target: "_blank",
                    }}
                  >
                    <Image
                      alt={"Youtube"}
                      height={"auto"}
                      loading={"lazy"}
                      src={
                        "https://uploads-ssl.webflow.com/62434fa732124a0fb112aab4/62434fa732124a717f12aaea_youtube%20small.svg"
                      }
                      width={"auto"}
                    />
                  </Link>
                </Block>
              </Block>
            </Grid>
          </Block>
          <Paragraph className={"paragraph-14"}>
            {
              "Grey is a financial technology company, not a bank. Banking services are provided by licensed banking partners"
            }
            <br />
            <br />
            {
              "Canadian services are offered by Aboki Finance Inc with registered address at 1285 West Broadway Suite 600 Vancouver BC V6H 3X8. Canada. Aboki Finance Inc. is regulated by FINTRAC."
            }
            <br />
            <br />
            {
              "US services are offered by Grey Inc. (formerly Aboki Africa Inc.) with its registered address at 651 N Broad St, Suite 206 Middletown DE 19709 US. Grey Inc is regulated by FinCEN."
            }
            <br />
            <br />
            {"Copyright © Grey Inc. 2023."}
          </Paragraph>
        </Container>
      </Section>
    </div>
  );
}
