/**
 * @generated
 * @file GetStartedSteps (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Image from "./webflow_modules/Basic/components/Image";

/**
 * Props for {@link GetStartedSteps}
 */
export type GetStartedStepsProps = {
  step1Image?: string;
  step1Label?: React.ReactNode;
  step1Text?: React.ReactNode;
  step2Image?: string;
  step2Label?: React.ReactNode;
  step2Text?: React.ReactNode;
  step3Image?: string;
  step3Label?: React.ReactNode;
  step3Text?: React.ReactNode;
  step4Image?: string;
  step4Label?: React.ReactNode;
  step4Text?: React.ReactNode;
};

/**
 * GetStartedSteps
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function GetStartedSteps({
  step1Image = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6973a82418ec7c7afaf206dd_download.avif",
  step1Label = "STEP ONE",
  step1Text = "Download the Grey app",
  step2Image = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6973a82572922db622c642cf_create.avif",
  step2Label = "STEP TWO",
  step2Text = "Create your account",
  step3Image = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6973a824a2a57d0abf89470a_fund.avif",
  step3Label = "STEP THREE",
  step3Text = "Fund your account",
  step4Image = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6973a825fe94a55e16bb0362_ready.avif",
  step4Label = "STEP FOUR",
  step4Text = "Create your card instantly",
}: GetStartedStepsProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"gyc-steps-wrapper"} tag={"div"}>
        <Block className={"gyc-step"} tag={"div"}>
          <Block className={"gyb-copy-wrapper"} tag={"div"}>
            <Block className={"gyc-step-id"} tag={"div"}>
              {step1Label}
            </Block>
            <Block className={"gyb-step-copy"} tag={"div"}>
              {step1Text}
            </Block>
          </Block>
          <Block className={"gyc-image-wrapper"} tag={"div"}>
            <Image
              alt={""}
              className={"gyb-image"}
              height={"590"}
              loading={"lazy"}
              src={step1Image}
              width={"588"}
            />
          </Block>
        </Block>
        <Block
          className={"gyc-step"}
          id={"w-node-_0c4f6743-cb8a-17b6-9c11-4a8f49c2eeb3-49c2eeaa"}
          tag={"div"}
        >
          <Block className={"gyb-copy-wrapper"} tag={"div"}>
            <Block className={"gyc-step-id"} tag={"div"}>
              {step2Label}
            </Block>
            <Block className={"gyb-step-copy"} tag={"div"}>
              {step2Text}
            </Block>
          </Block>
          <Block className={"gyc-image-wrapper"} tag={"div"}>
            <Image
              alt={""}
              className={"gyb-image"}
              height={"590"}
              loading={"lazy"}
              src={step2Image}
              width={"588"}
            />
          </Block>
        </Block>
        <Block
          className={"gyc-step"}
          id={"w-node-_0c4f6743-cb8a-17b6-9c11-4a8f49c2eebb-49c2eeaa"}
          tag={"div"}
        >
          <Block className={"gyb-copy-wrapper"} tag={"div"}>
            <Block className={"gyc-step-id"} tag={"div"}>
              {step3Label}
            </Block>
            <Block className={"gyb-step-copy"} tag={"div"}>
              {step3Text}
            </Block>
          </Block>
          <Block className={"gyc-image-wrapper"} tag={"div"}>
            <Image
              alt={""}
              className={"gyb-image"}
              height={"590"}
              loading={"lazy"}
              src={step3Image}
              width={"588"}
            />
          </Block>
        </Block>
        <Block
          className={"gyc-step"}
          id={"w-node-_0c4f6743-cb8a-17b6-9c11-4a8f49c2eec3-49c2eeaa"}
          tag={"div"}
        >
          <Block className={"gyb-copy-wrapper"} tag={"div"}>
            <Block className={"gyc-step-id"} tag={"div"}>
              {step4Label}
            </Block>
            <Block className={"gyb-step-copy"} tag={"div"}>
              {step4Text}
            </Block>
          </Block>
          <Block className={"gyc-image-wrapper"} tag={"div"}>
            <Image
              alt={""}
              className={"gyb-image"}
              height={"590"}
              loading={"lazy"}
              src={step4Image}
              width={"588"}
            />
          </Block>
        </Block>
      </Block>
    </div>
  );
}
