/**
 * @generated
 * @file HowToOpenAccount (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Container from "./webflow_modules/Layout/components/Container";
import Grid from "./webflow_modules/Layout/components/Grid";
import Heading from "./webflow_modules/Basic/components/Heading";
import Link from "./webflow_modules/Basic/components/Link";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link HowToOpenAccount}
 */
export type HowToOpenAccountProps = {
  heading2Text?: React.ReactNode;
  heading6Text?: React.ReactNode;
  paragraph10Text?: React.ReactNode;
  paragraph10Text2?: React.ReactNode;
  paragraph10Text3?: React.ReactNode;
  paragraph9Text?: React.ReactNode;
  paragraph9Text2?: React.ReactNode;
  subHeaderText?: React.ReactNode;
};

/**
 * HowToOpenAccount
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function HowToOpenAccount({
  heading2Text = "How to open a free foreign bank account",
  heading6Text = "Complete KYC verification",
  paragraph10Text = "Sign up online, or in our app with your email address",
  paragraph10Text2 = "Verify your identity using your government-issued ID",
  paragraph10Text3 = "Share your account details to get paid, or spend around the world with your debit card.",
  paragraph9Text = "Register in minutes",
  paragraph9Text2 = "Get your virtual account",
  subHeaderText = "Opening an account has never been this seamless.",
}: HowToOpenAccountProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"wrapper gradient"}
        grid={{
          type: "section",
        }}
        tag={"div"}
      >
        <Container className={"open_an_account-wrapper max-width"} tag={"div"}>
          <Block className={"header_and_sub"} tag={"div"}>
            <Heading className={"heading-2"} tag={"h1"}>
              {heading2Text}
            </Heading>
            <Paragraph className={"sub-header"}>{subHeaderText}</Paragraph>
          </Block>
          <Grid className={"grid"} tag={"div"}>
            <Block
              className={"open_an_account"}
              id={"w-node-_33f62830-b1a0-3d4c-37a4-563e14340edb-14340ed3"}
              tag={"div"}
            >
              <Block className={"div-block-16"} tag={"div"}>
                <Paragraph className={"paragraph-8"}>{"1"}</Paragraph>
              </Block>
              <Paragraph className={"paragraph-9"}>{paragraph9Text}</Paragraph>
              <Paragraph className={"paragraph-10"}>
                {paragraph10Text}
              </Paragraph>
            </Block>
            <Block
              className={"open_an_account"}
              id={"w-node-_33f62830-b1a0-3d4c-37a4-563e14340ee3-14340ed3"}
              tag={"div"}
            >
              <Block className={"div-block-16"} tag={"div"}>
                <Paragraph className={"paragraph-8"}>{"2"}</Paragraph>
              </Block>
              <Paragraph className={"heading-6"}>{heading6Text}</Paragraph>
              <Paragraph className={"paragraph-10"}>
                {paragraph10Text2}
              </Paragraph>
            </Block>
            <Block
              className={"open_an_account"}
              id={"w-node-_33f62830-b1a0-3d4c-37a4-563e14340eeb-14340ed3"}
              tag={"div"}
            >
              <Block className={"div-block-16"} tag={"div"}>
                <Paragraph className={"paragraph-8"}>{"3"}</Paragraph>
              </Block>
              <Paragraph className={"paragraph-9"}>{paragraph9Text2}</Paragraph>
              <Paragraph className={"paragraph-10"}>
                {paragraph10Text3}
              </Paragraph>
            </Block>
          </Grid>
          <Link
            button={true}
            className={"button dark"}
            options={{
              href: "#",
              target: "_blank",
            }}
          >
            {"Get started — for free"}
          </Link>
        </Container>
      </Section>
    </div>
  );
}
