/**
 * @generated
 * @file InvoiceVp (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Image from "./webflow_modules/Basic/components/Image";

/**
 * Props for {@link InvoiceVp}
 */
export type InvoiceVpProps = {
  image?: string;
  text1?: React.ReactNode;
  text2?: React.ReactNode;
};

/**
 * InvoiceVp
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function InvoiceVp({
  image = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/672a1d829ff1198b5c0fc42d_digitalSignup.svg",
  text1 = "100% digital signup",
  text2 = "Open your bank account in minutes",
}: InvoiceVpProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"everythinginvoice"} tag={"div"}>
        <Image
          alt={""}
          className={"invoice-vp-img"}
          height={"48"}
          loading={"lazy"}
          src={image}
          width={"48"}
        />
        <Block className={" invoiceperktitle"} tag={"div"}>
          {text1}
        </Block>
        <Block className={" invoicetextsupport"} tag={"div"}>
          {text2}
        </Block>
      </Block>
    </div>
  );
}
