/**
 * @generated
 * @file MobileAppBanner (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Container from "./webflow_modules/Layout/components/Container";
import Heading from "./webflow_modules/Basic/components/Heading";
import Link from "./webflow_modules/Basic/components/Link";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link MobileAppBanner}
 */
export type MobileAppBannerProps = {};

/**
 * MobileAppBanner
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function MobileAppBanner({}: MobileAppBannerProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"wrapper dark"}
        grid={{
          type: "section",
        }}
        tag={"div"}
      >
        <Container className={"app-showcase max-width"} tag={"div"}>
          <Block className={"div-block-23"} tag={"div"}>
            <Block className={"div-block-24"} tag={"div"}>
              <Block tag={"div"}>
                <Heading className={"heading-9"} tag={"h1"}>
                  {"Get digital banking at your fingertips"}
                </Heading>
                <Paragraph className={"sub-header centred"}>
                  {"Get our mobile app on any device you use on the"}
                  <br />
                  {"App Store or Google Playstore"}
                </Paragraph>
              </Block>
              <Block className={"app_store-icons"} tag={"div"}>
                <Link
                  block={"inline"}
                  button={false}
                  className={"store-link android"}
                  options={{
                    href: "https://link.grey.co/androidapp",
                    target: "_blank",
                  }}
                />
                <Link
                  block={"inline"}
                  button={false}
                  className={"store-link"}
                  options={{
                    href: "https://link.grey.co/iOSapp",
                    target: "_blank",
                  }}
                />
              </Block>
            </Block>
            <Block className={"div-block-25"} tag={"div"}>
              <Block className={"div-block-26"} tag={"div"} />
            </Block>
          </Block>
        </Container>
      </Section>
    </div>
  );
}
