/**
 * @generated
 * @file NewsletterSubscription (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Container from "./webflow_modules/Layout/components/Container";
import FormBlockLabel from "./webflow_modules/Form/components/FormBlockLabel";
import FormButton from "./webflow_modules/Form/components/FormButton";
import FormErrorMessage from "./webflow_modules/Form/components/FormErrorMessage";
import FormForm from "./webflow_modules/Form/components/FormForm";
import FormSelect from "./webflow_modules/Form/components/FormSelect";
import FormSuccessMessage from "./webflow_modules/Form/components/FormSuccessMessage";
import FormTextInput from "./webflow_modules/Form/components/FormTextInput";
import FormWrapper from "./webflow_modules/Form/components/FormWrapper";
import HtmlEmbed from "./webflow_modules/Embed/components/HtmlEmbed";
import Image from "./webflow_modules/Basic/components/Image";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link NewsletterSubscription}
 */
export type NewsletterSubscriptionProps = {};

/**
 * NewsletterSubscription
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function NewsletterSubscription({}: NewsletterSubscriptionProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"section-wrapper section form"}
        grid={{
          type: "section",
        }}
        id={"blog-subscription"}
        tag={"section"}
      >
        <Block className={"div-block-166"} tag={"div"}>
          <Container className={"wrapper-2"} tag={"div"}>
            <FormWrapper className={"blogsubscription"}>
              <FormForm
                className={"footer-form-container-two-2"}
                data-name={"Newsletter Subscription"}
                id={"wf-form-Newsletter-Subscription-2"}
                method={"get"}
                name={"wf-form-Newsletter-Subscription-2"}
              >
                <Block className={"div-block-180"} tag={"div"}>
                  <Block className={"text-block-79"} tag={"div"}>
                    {"Join our"}
                    <br />
                    {"freelancer network today"}
                  </Block>
                  <Paragraph className={"paragraph29"}>
                    {
                      "Be the first to know about our freelancing events, gigs, opportunities and news when you subscribe to our mailing list"
                    }
                  </Paragraph>
                </Block>
                <Block className={"footer-form-block-two long"} tag={"div"}>
                  <Block className={"div-block-181"} tag={"div"}>
                    <FormBlockLabel
                      className={"bloglabel"}
                      htmlFor={"firstName"}
                    >
                      {"First name"}
                    </FormBlockLabel>
                    <FormTextInput
                      autoFocus={false}
                      className={"emailcontainer blog"}
                      data-name={"firstName"}
                      disabled={false}
                      id={"firstName"}
                      maxLength={256}
                      name={"firstName"}
                      placeholder={"Enter your first name"}
                      required={true}
                      type={"text"}
                    />
                  </Block>
                  <Block className={"div-block-181"} tag={"div"}>
                    <FormBlockLabel
                      className={"bloglabel"}
                      htmlFor={"lastName"}
                    >
                      {"Last name"}
                    </FormBlockLabel>
                    <FormTextInput
                      autoFocus={false}
                      className={"emailcontainer blog"}
                      data-name={"lastName"}
                      disabled={false}
                      id={"lastName"}
                      maxLength={256}
                      name={"lastName"}
                      placeholder={"Enter your last name"}
                      required={true}
                      type={"text"}
                    />
                  </Block>
                  <Block className={"div-block-181"} tag={"div"}>
                    <FormBlockLabel
                      className={"bloglabel"}
                      htmlFor={"emailAddress"}
                    >
                      {"Email"}
                    </FormBlockLabel>
                    <FormTextInput
                      autoFocus={false}
                      className={"emailcontainer blog"}
                      data-name={"emailAddress"}
                      disabled={false}
                      id={"emailAddress"}
                      maxLength={256}
                      name={"emailAddress"}
                      placeholder={"Enter your email address"}
                      required={true}
                      type={"text"}
                    />
                  </Block>
                  <Block className={"div-block-181"} tag={"div"}>
                    <FormBlockLabel
                      className={"bloglabel"}
                      htmlFor={"Email-address-2"}
                    >
                      {"Country"}
                    </FormBlockLabel>
                    <Block
                      className={"countrydropdownblogcontainer-2"}
                      tag={"div"}
                    >
                      <FormSelect
                        className={"countrydropdownblog-2"}
                        data-name={"countryFooter"}
                        id={"countryFooter"}
                        multiple={false}
                        name={"countryFooter"}
                        options={[
                          {
                            t: "Select country",
                            v: "",
                          },
                          {
                            t: "Algeria",
                            v: "DZ",
                          },
                          {
                            t: "Angola",
                            v: "AO",
                          },
                          {
                            t: "Argetina",
                            v: "AR",
                          },
                          {
                            t: "Australia",
                            v: "AU",
                          },
                          {
                            t: "Austria",
                            v: "AT",
                          },
                          {
                            t: "Belgium",
                            v: "BE",
                          },
                          {
                            t: "Benin",
                            v: "BJ",
                          },
                          {
                            t: "Brazil",
                            v: "BR",
                          },
                          {
                            t: "Bulgaria",
                            v: "BG",
                          },
                          {
                            t: "Cameroon",
                            v: "CM",
                          },
                          {
                            t: "Canada",
                            v: "CA",
                          },
                          {
                            t: "Chile",
                            v: "CL",
                          },
                          {
                            t: "Colombia",
                            v: "CO",
                          },
                          {
                            t: "Cote d'Ivoire",
                            v: "CI",
                          },
                          {
                            t: "Croatia",
                            v: "HR",
                          },
                          {
                            t: "Cyprus",
                            v: "CY",
                          },
                          {
                            t: "Czech Republic",
                            v: "CZ",
                          },
                          {
                            t: "Denmark",
                            v: "DK",
                          },
                          {
                            t: "Egypt",
                            v: "EG",
                          },
                          {
                            t: "Estonia",
                            v: "EE",
                          },
                          {
                            t: "Finland",
                            v: "FI",
                          },
                          {
                            t: "France",
                            v: "FR",
                          },
                          {
                            t: "Germany",
                            v: "DE",
                          },
                          {
                            t: "Ghana",
                            v: "GH",
                          },
                          {
                            t: "Greece",
                            v: "GR",
                          },
                          {
                            t: "Holy See",
                            v: "VA",
                          },
                          {
                            t: "Hong Kong",
                            v: "HK",
                          },
                          {
                            t: "Hungary",
                            v: "HU",
                          },
                          {
                            t: "Ireland",
                            v: "IE",
                          },
                          {
                            t: "India",
                            v: "IN",
                          },
                          {
                            t: "Indonesia",
                            v: "ID",
                          },
                          {
                            t: "Italy",
                            v: "IT",
                          },
                          {
                            t: "Kenya",
                            v: "KE",
                          },
                          {
                            t: "Latvia",
                            v: "LV",
                          },
                          {
                            t: "Lithuania",
                            v: "LT",
                          },
                          {
                            t: "Luxembourg",
                            v: "LU",
                          },
                          {
                            t: "Malta",
                            v: "MT",
                          },
                          {
                            t: "Malaysia",
                            v: "MY",
                          },
                          {
                            t: "Mexico",
                            v: "MX",
                          },
                          {
                            t: "Moldova",
                            v: "MD",
                          },
                          {
                            t: "Monaco",
                            v: "MC",
                          },
                          {
                            t: "Morocco",
                            v: "MA",
                          },
                          {
                            t: "Namibia",
                            v: "NA",
                          },
                          {
                            t: "Netherlands",
                            v: "NL",
                          },
                          {
                            t: "New Zealand",
                            v: "NZ",
                          },
                          {
                            t: "Nigeria",
                            v: "NG",
                          },
                          {
                            t: "Norway",
                            v: "NO",
                          },
                          {
                            t: "Peru",
                            v: "PE",
                          },
                          {
                            t: "Philippines",
                            v: "PH",
                          },
                          {
                            t: "Poland",
                            v: "PL",
                          },
                          {
                            t: "Portugal",
                            v: "PT",
                          },
                          {
                            t: "Romania",
                            v: "RO",
                          },
                          {
                            t: "Rwanda",
                            v: "RW",
                          },
                          {
                            t: "San Marino",
                            v: "SM",
                          },
                          {
                            t: "Saudi Arabia",
                            v: "SA",
                          },
                          {
                            t: "Senegal",
                            v: "SN",
                          },
                          {
                            t: "Singapore",
                            v: "SG",
                          },
                          {
                            t: "Slovenia",
                            v: "SI",
                          },
                          {
                            t: "South Africa",
                            v: "ZA",
                          },
                          {
                            t: "Spain",
                            v: "ES",
                          },
                          {
                            t: "Sweden",
                            v: "SE",
                          },
                          {
                            t: "Switzerland",
                            v: "CH",
                          },
                          {
                            t: "Tanzania",
                            v: "TZ",
                          },
                          {
                            t: "Thailand",
                            v: "TH",
                          },
                          {
                            t: "Togo",
                            v: "TG",
                          },
                          {
                            t: "Turkey",
                            v: "TR",
                          },
                          {
                            t: "Uganda",
                            v: "UG",
                          },
                          {
                            t: "United States of America",
                            v: "US",
                          },
                          {
                            t: "Uruguay",
                            v: "UY",
                          },
                          {
                            t: "United Arab Emirates",
                            v: "AE",
                          },
                          {
                            t: "United Kingdom",
                            v: "GB",
                          },
                          {
                            t: "Vietnam",
                            v: "VN",
                          },
                          {
                            t: "Zambia",
                            v: "ZM",
                          },
                        ]}
                        required={true}
                      />
                      <Image
                        alt={"drop arrow"}
                        className={"dropdownarrowicon invert"}
                        height={"auto"}
                        loading={"lazy"}
                        src={
                          "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/63754bf26e3ec367bc343968_drop-arrow.svg"
                        }
                        width={"auto"}
                      />
                      <HtmlEmbed
                        content={
                          "<style>\n/* Hide default select dropdown arrow */\nselect {\n  -webkit-appearance: none;\n  -moz-appearance: none;\n\t}\n\n</style>"
                        }
                      />
                    </Block>
                  </Block>
                  <FormButton
                    className={"_404button blog"}
                    data-wait={"Please wait..."}
                    type={"submit"}
                    value={"Subscribe to newsletter"}
                  />
                </Block>
              </FormForm>
              <FormSuccessMessage className={"success-message"}>
                <Block className={"successmessagecontainer"} tag={"div"}>
                  <Block className={"successicon"} tag={"div"} />
                  <Block className={"successmessagecontent"} tag={"div"}>
                    <Block className={"successheader"} tag={"div"}>
                      {"Check your inbox! 😀"}
                    </Block>
                    <Block className={"successbody"} tag={"div"}>
                      {
                        "We've sent you a confirmation email. Just follow the steps to complete your subscription."
                      }
                    </Block>
                  </Block>
                </Block>
              </FormSuccessMessage>
              <FormErrorMessage className={"error-message-2"}>
                <Block className={" form-error-text"} tag={"div"}>
                  {"Oops! Something went wrong while submitting the form."}
                </Block>
              </FormErrorMessage>
            </FormWrapper>
          </Container>
        </Block>
      </Section>
    </div>
  );
}
