/**
 * @generated
 * @file Resources (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Container from "./webflow_modules/Layout/components/Container";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";
import NotSupported from "./webflow_modules/Builtin/components/NotSupported";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link Resources}
 */
export type ResourcesProps = {};

/**
 * Resources
 *
 * @warning
 * The component could not be fully exported:
 * - Unsupported element: `Collection List`
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function Resources({}: ResourcesProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"wrapper colored"}
        grid={{
          type: "section",
        }}
        tag={"div"}
      >
        <Container className={"resources-wrapper max-width"} tag={"div"}>
          <Block className={"header_and_sub"} tag={"div"}>
            <Heading className={"heading-2"} tag={"h2"}>
              {"Resources to learn more about how Grey works"}
            </Heading>
            <Paragraph className={"sub-header"}>
              {
                "Expertly curated articles to help you understand how our foreign accounts work."
              }
            </Paragraph>
          </Block>
          <Block className={"div-block-37"} tag={"div"}>
            <NotSupported _atom={"Collection List"} />
          </Block>
        </Container>
      </Section>
    </div>
  );
}
