/**
 * @generated
 * @file SendBlock13 (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import BlockContainer from "./webflow_modules/Layout/components/BlockContainer";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link SendBlock13}
 */
export type SendBlock13Props = {
  block13Body?: React.ReactNode;
  block13BodyIi?: React.ReactNode;
  image1?: string;
  image2?: string;
  image3?: string;
  link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  text?: React.ReactNode;
};

/**
 * SendBlock13
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function SendBlock13({
  block13Body = "Heading",
  block13BodyIi = "This is some text inside of a div block.",
  image1 = "",
  image2 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/67f8f68b6a43a328b669a59c_4632949cb6e5e84e75bc4b053891115f_handWithPhone.avif",
  image3 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6563d397fe1528274b629ba3_bg%20vector.svg",

  link = {
    href: "https://app.grey.co/auth/register",
  },

  text = "Open a free Grey account",
}: SendBlock13Props) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"new-section grey"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <BlockContainer
          className={"new-section-container-11"}
          grid={{
            type: "container",
          }}
          tag={"div"}
        >
          <Block className={"global-account-section"} tag={"div"}>
            <Block className={"new-section-wrapper is-flex-start"} tag={"div"}>
              <Image
                alt={""}
                className={"grey-badge"}
                height={"auto"}
                loading={"lazy"}
                src={image1}
                width={"auto"}
              />
              <Heading
                className={"new-section-heading_ii is-align-left"}
                tag={"h2"}
              >
                {block13Body}
              </Heading>
              <Block className={"spacer-1-3"} tag={"div"} />
              <Block className={"new-subheading is-align-left"} tag={"div"}>
                {block13BodyIi}
              </Block>
            </Block>
            <Image
              alt={""}
              className={"global-account-image"}
              height={"auto"}
              loading={"lazy"}
              src={image2}
              width={"auto"}
            />
            <Link
              block={"inline"}
              button={false}
              className={"newbutton-3"}
              options={link}
            >
              <Block className={"newbutton_label"} tag={"div"}>
                {text}
              </Block>
            </Link>
          </Block>
        </BlockContainer>
        <Image
          alt={""}
          className={"bg-gradient"}
          height={"auto"}
          loading={"lazy"}
          src={image3}
          width={"auto"}
        />
      </Section>
    </div>
  );
}
