/**
 * @generated
 * @file SendBlock12Parent (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import BlockContainer from "./webflow_modules/Layout/components/BlockContainer";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import RichText from "./webflow_modules/Basic/components/RichText";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link SendBlock12Parent}
 */
export type SendBlock12ParentProps = {
  block12Bodyy?: React.ReactNode;
  block12GridItem1Bodyy?: React.ReactNode;
  block12GridItem2Bodyy?: React.ReactNode;
  block12GridItem3Bodyy?: React.ReactNode;
  block12GridItem4Bodyy?: React.ReactNode;
  block12Headingg?: React.ReactNode;
  image1?: string;
  image2?: string;
  image3?: string;
  image4?: string;
};

/**
 * SendBlock12Parent
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function SendBlock12Parent({
  block12Bodyy = "",
  block12GridItem1Bodyy = "This is some text inside of a div block.",
  block12GridItem2Bodyy = "This is some text inside of a div block.",
  block12GridItem3Bodyy = "This is some text inside of a div block.",
  block12GridItem4Bodyy = "This is some text inside of a div block.",
  block12Headingg = "Heading",
  image1 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/67f3c84e0f92a62c83bd8fd6_Bank3d.avif",
  image2 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/67f3c84e0f92a62c83bd8fd6_Bank3d.avif",
  image3 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/67f3c84e0f92a62c83bd8fd6_Bank3d.avif",
  image4 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/67f3c84e0f92a62c83bd8fd6_Bank3d.avif",
}: SendBlock12ParentProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"new-section _w-padding _w-noise allow-overflow"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <BlockContainer
          className={"new-section-container"}
          grid={{
            type: "container",
          }}
          tag={"div"}
        >
          <Block className={"div-block-304"} tag={"div"}>
            <Heading className={"new-section-heading is-50"} tag={"h2"}>
              {block12Headingg}
            </Heading>
            <RichText
              className={"new-subheading prog is-align-left"}
              tag={"div"}
            >
              {block12Bodyy}
            </RichText>
          </Block>
          <Block className={"div-block-305"} tag={"div"}>
            <Block className={"div-block-306"} tag={"div"}>
              <Block className={"div-block-307"} tag={"div"}>
                <Image
                  alt={""}
                  className={"image-208"}
                  height={"auto"}
                  loading={"lazy"}
                  src={image1}
                  width={"auto"}
                />
                <Block className={"prog-hc-body"} tag={"div"}>
                  {block12GridItem1Bodyy}
                </Block>
              </Block>
              <Block
                className={"div-block-307"}
                id={"w-node-ed7437c8-4e67-b8e3-27de-dbe5cdd8ad39-cdd8ad2f"}
                tag={"div"}
              >
                <Image
                  alt={""}
                  className={"image-208"}
                  height={"auto"}
                  loading={"lazy"}
                  src={image2}
                  width={"auto"}
                />
                <Block className={"prog-hc-body"} tag={"div"}>
                  {block12GridItem2Bodyy}
                </Block>
              </Block>
              <Block
                className={"div-block-307"}
                id={"w-node-ed7437c8-4e67-b8e3-27de-dbe5cdd8ad3c-cdd8ad2f"}
                tag={"div"}
              >
                <Image
                  alt={""}
                  className={"image-208"}
                  height={"auto"}
                  loading={"lazy"}
                  src={image3}
                  width={"auto"}
                />
                <Block className={"prog-hc-body"} tag={"div"}>
                  {block12GridItem3Bodyy}
                </Block>
              </Block>
              <Block
                className={"div-block-307"}
                id={"w-node-ed7437c8-4e67-b8e3-27de-dbe5cdd8ad3f-cdd8ad2f"}
                tag={"div"}
              >
                <Image
                  alt={""}
                  className={"image-208"}
                  height={"auto"}
                  loading={"lazy"}
                  src={image4}
                  width={"auto"}
                />
                <Block className={"prog-hc-body"} tag={"div"}>
                  {block12GridItem4Bodyy}
                </Block>
              </Block>
            </Block>
          </Block>
        </BlockContainer>
      </Section>
    </div>
  );
}
