/**
 * @generated
 * @file SendBlock3 (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import BlockContainer from "./webflow_modules/Layout/components/BlockContainer";
import Heading from "./webflow_modules/Basic/components/Heading";
import HtmlEmbed from "./webflow_modules/Embed/components/HtmlEmbed";
import Image from "./webflow_modules/Basic/components/Image";
import RichText from "./webflow_modules/Basic/components/RichText";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link SendBlock3}
 */
export type SendBlock3Props = {
  block3BodyIi?: React.ReactNode;
  block3Heading?: React.ReactNode;
  image?: string;
};

/**
 * SendBlock3
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function SendBlock3({
  block3BodyIi = "",
  block3Heading = "Heading",
  image = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a46cca8bcd1aac4234f96d7_clouds.avif",
}: SendBlock3Props) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"new-section _w-padding"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <BlockContainer
          className={"new-section-container"}
          grid={{
            type: "container",
          }}
          tag={"div"}
        >
          <Block className={"contentcontainer"} tag={"div"}>
            <Block className={"features-section"} tag={"div"}>
              <Block className={"send-abroad-content"} tag={"div"}>
                <Heading className={"send-abroad"} tag={"h2"}>
                  {block3Heading}
                </Heading>
                <RichText
                  className={"new-subheading is-align-left no-margin"}
                  tag={"div"}
                >
                  {block3BodyIi}
                </RichText>
              </Block>
            </Block>
          </Block>
        </BlockContainer>
        <Image
          alt={""}
          className={"prog-send-abroad"}
          height={"3648"}
          loading={"lazy"}
          src={image}
          width={"5472"}
        />
      </Section>
    </div>
  );
}
