/**
 * @generated
 * @file SendRelatedCountries (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";

/**
 * Props for {@link SendRelatedCountries}
 */
export type SendRelatedCountriesProps = {
  block12FlagImg?: string;
  currentPageLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  destinationCountryName?: React.ReactNode;
  showRelatedCountries?: boolean;
};

/**
 * SendRelatedCountries
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function SendRelatedCountries({
  block12FlagImg = "",

  currentPageLink = {
    href: "#",
  },

  destinationCountryName = "Heading",
  showRelatedCountries = true,
}: SendRelatedCountriesProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {showRelatedCountries ? (
        <Link
          block={"inline"}
          button={false}
          className={"link-block-7"}
          options={currentPageLink}
        >
          <Image
            alt={""}
            className={"image-201"}
            height={"45"}
            loading={"lazy"}
            src={block12FlagImg}
            width={"45"}
          />
          <Block className={"destination-label-wrap"} tag={"div"}>
            <Block className={"more-destinations-label"} tag={"div"}>
              {"Send money to"}
            </Block>
            <Block className={"more-destinations-label"} tag={"div"}>
              {destinationCountryName}
            </Block>
          </Block>
        </Link>
      ) : null}
    </div>
  );
}
