/**
 * @generated
 * @file SendReviewScore (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import Image from "./webflow_modules/Basic/components/Image";

/**
 * Props for {@link SendReviewScore}
 */
export type SendReviewScoreProps = {
  image1?: string;
  image2?: string;
  text1?: React.ReactNode;
  text2?: React.ReactNode;
  text3?: React.ReactNode;
  text4?: React.ReactNode;
  text5?: React.ReactNode;
  text6?: React.ReactNode;
  text7?: React.ReactNode;
};

/**
 * SendReviewScore
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function SendReviewScore({
  image1 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a3e9402f964d136cbcbe7a2_playstore.svg",
  image2 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a3e9403cd6d0f58823ab94e_appstore.svg",
  text1 = "Trusted by 3M+ people around the world",
  text2 = "4.7",
  text3 = "/5.0",
  text4 = "GOOGLE PLAY •22K REVIEWS",
  text5 = "4.6",
  text6 = "/5.0",
  text7 = "APP STORE • 12K REVIEWS",
}: SendReviewScoreProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Block className={"store-review-wrapper"} tag={"div"}>
        <Block className={"label is-grey"} tag={"div"}>
          {text1}
        </Block>
        <Block className={"store-review"} tag={"div"}>
          <Block className={"review"} tag={"div"}>
            <Block className={"review-rating-container"} tag={"div"}>
              <Image
                alt={""}
                className={"app-review-logo"}
                height={"auto"}
                loading={"lazy"}
                src={image1}
                width={"auto"}
              />
              <Block className={"review-rating"} tag={"div"}>
                <Block className={"text-block-12"} tag={"div"}>
                  {text2}
                </Block>
                <Block className={"text-block-13"} tag={"div"}>
                  {text3}
                </Block>
              </Block>
            </Block>
            <Block className={"review-store-name"} tag={"div"}>
              {text4}
            </Block>
          </Block>
          <Block className={"ratings-divider"} tag={"div"} />
          <Block className={"review"} tag={"div"}>
            <Block className={"review-rating-container"} tag={"div"}>
              <Image
                alt={""}
                className={"app-review-logo"}
                height={"auto"}
                loading={"lazy"}
                src={image2}
                width={"auto"}
              />
              <Block className={"review-rating"} tag={"div"}>
                <Block className={"text-block-12"} tag={"div"}>
                  {text5}
                </Block>
                <Block className={"text-block-13"} tag={"div"}>
                  {text6}
                </Block>
              </Block>
            </Block>
            <Block className={"review-store-name"} tag={"div"}>
              {text7}
            </Block>
          </Block>
        </Block>
      </Block>
    </div>
  );
}
