/**
 * @generated
 * @file SendBlock7 (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import BlockContainer from "./webflow_modules/Layout/components/BlockContainer";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import RichText from "./webflow_modules/Basic/components/RichText";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link SendBlock7}
 */
export type SendBlock7Props = {
  block7Body?: React.ReactNode;
  block7Heading?: React.ReactNode;
  image?: string;
};

/**
 * SendBlock7
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function SendBlock7({
  block7Body = "",
  block7Heading = "Heading",
  image = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a4d0eabc27f34a28724dcb2_fast-provider.avif",
}: SendBlock7Props) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"new-section _w-padding _w-noise"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <BlockContainer
          className={"new-section-container"}
          grid={{
            type: "container",
          }}
          tag={"div"}
        >
          <Block className={"div-block-309"} tag={"div"}>
            <Image
              alt={""}
              className={"image-209"}
              height={"400"}
              loading={"lazy"}
              src={image}
              width={"400"}
            />
            <Block className={"div-block-308"} tag={"div"}>
              <Heading
                className={"new-section-heading is-align-left"}
                tag={"h2"}
              >
                {block7Heading}
              </Heading>
              <RichText
                className={"new-subheading is-align-left is-100"}
                tag={"div"}
              >
                {block7Body}
              </RichText>
            </Block>
          </Block>
        </BlockContainer>
      </Section>
    </div>
  );
}
