/**
 * @generated
 * @file SendBlock2 (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import BlockContainer from "./webflow_modules/Layout/components/BlockContainer";
import Heading from "./webflow_modules/Basic/components/Heading";
import HtmlEmbed from "./webflow_modules/Embed/components/HtmlEmbed";
import Image from "./webflow_modules/Basic/components/Image";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link SendBlock2}
 */
export type SendBlock2Props = {
  block2FundBody?: React.ReactNode;
  block2GridItem1Heading?: React.ReactNode;
  block2GridItem2Heading?: React.ReactNode;
  block2GridItem3Heading?: React.ReactNode;
  block2Heading?: React.ReactNode;
  block2SendBody?: React.ReactNode;
  block2SignUpBody?: React.ReactNode;
  image1?: string;
  image2?: string;
  image3?: string;
  image4?: string;
  image5?: string;
};

/**
 * SendBlock2
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function SendBlock2({
  block2FundBody = "This is some text inside of a div block.",
  block2GridItem1Heading = "Heading",
  block2GridItem2Heading = "Heading",
  block2GridItem3Heading = "Heading",
  block2Heading = "Heading",
  block2SendBody = "This is some text inside of a div block.",
  block2SignUpBody = "This is some text inside of a div block.",
  image1 = "",
  image2 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/67ffe1a5737a10dbc49789c5_card1.svg",
  image3 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/69fcf3613e47a9244c5d4871_registerhere.png",
  image4 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/67ffe2cf5a316567b65aca73_card2.svg",
  image5 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/67ffe0853cb596bb6b8552c3_card3.svg",
}: SendBlock2Props) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"new-section _w-padding _w-noise"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <BlockContainer
          className={"new-section-container-10"}
          grid={{
            type: "container",
          }}
          tag={"div"}
        >
          <Block
            className={"section-heading-wrapper-7 flex-down center"}
            tag={"div"}
          >
            <Image
              alt={""}
              className={"grey-badge"}
              height={"auto"}
              loading={"lazy"}
              src={image1}
              width={"auto"}
            />
            <Heading className={"new-section-heading_ii"} tag={"h2"}>
              {block2Heading}
            </Heading>
          </Block>
          <Block className={"s2-body"} tag={"div"}>
            <Block className={"feature-card ghana-landing"} tag={"div"}>
              <Block className={"illustration purple"} tag={"div"}>
                <Block className={"card-heading"} tag={"div"}>
                  <Image
                    alt={""}
                    height={"auto"}
                    loading={"lazy"}
                    src={image2}
                    width={"auto"}
                  />
                </Block>
                <Image
                  alt={"Grey foreign bank account in Ghana"}
                  className={"illust-img bdt _1"}
                  height={"Auto"}
                  loading={"lazy"}
                  src={image3}
                  width={"Auto"}
                />
                <Block className={"bottom-gradient purple"} tag={"div"} />
              </Block>
              <Block className={"fcard-heading ghana-landing"} tag={"div"}>
                <Heading
                  className={"feature-card-heading ghana-landing"}
                  tag={"h5"}
                >
                  {block2GridItem1Heading}
                </Heading>
                <Block
                  className={"feature-card-body is-grey center"}
                  tag={"div"}
                >
                  {block2SignUpBody}
                </Block>
              </Block>
            </Block>
            <Block className={"feature-card ghana-landing"} tag={"div"}>
              <Block className={"illustration blue"} tag={"div"}>
                <Block className={"card-heading"} tag={"div"}>
                  <Image
                    alt={""}
                    height={"auto"}
                    loading={"lazy"}
                    src={image4}
                    width={"auto"}
                  />
                </Block>
                <Block className={"illust-img bdt _2"} tag={"div"} />
                <Block className={"bottom-gradient blue"} tag={"div"} />
              </Block>
              <Block className={"fcard-heading ghana-landing"} tag={"div"}>
                <Heading
                  className={"feature-card-heading ghana-landing"}
                  tag={"h5"}
                >
                  {block2GridItem2Heading}
                </Heading>
                <Block
                  className={"feature-card-body is-grey center"}
                  tag={"div"}
                >
                  {block2FundBody}
                </Block>
              </Block>
            </Block>
            <Block className={"feature-card ghana-landing"} tag={"div"}>
              <Block className={"illustration three-copy"} tag={"div"}>
                <Block className={"card-heading"} tag={"div"}>
                  <Image
                    alt={""}
                    height={"auto"}
                    loading={"lazy"}
                    src={image5}
                    width={"auto"}
                  />
                </Block>
                <Block className={"illust-img _2 prog"} tag={"div"} />
                <Block className={"bottom-gradient three-copy"} tag={"div"} />
              </Block>
              <Block className={"fcard-heading ghana-landing"} tag={"div"}>
                <Heading
                  className={"feature-card-heading ghana-landing"}
                  tag={"h5"}
                >
                  {block2GridItem3Heading}
                </Heading>
                <Block
                  className={"feature-card-body is-grey center"}
                  tag={"div"}
                >
                  {block2SendBody}
                </Block>
              </Block>
            </Block>
          </Block>
        </BlockContainer>
      </Section>
    </div>
  );
}
