/**
 * @generated
 * @file SendRelatedCountries (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import HtmlEmbed from "./webflow_modules/Embed/components/HtmlEmbed";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";

/**
 * Props for {@link SendRelatedCountries}
 */
export type SendRelatedCountriesProps = {
  block12FlagImg?: string;
  currentPageLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  destinationCountryName?: React.ReactNode;
  linkTextOne?: React.ReactNode;
  linkTextThree?: React.ReactNode;
  originCountryName?: React.ReactNode;
  showRelatedCountries?: boolean;
  variant?: "Base" | "Parent";
};

/**
 * SendRelatedCountries
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function SendRelatedCountries({
  block12FlagImg = "",

  currentPageLink = {
    href: "#",
  },

  destinationCountryName = "Heading",
  linkTextOne = "Send money to",
  linkTextThree = "Send money to",
  originCountryName = "Send money to",
  showRelatedCountries = true,
  variant = "Base",
}: SendRelatedCountriesProps) {
  const _styleVariantMap = {
    Base: "",
    Parent: "w-variant-dd4de953-c839-bc29-52a1-fd07a8466990",
  };

  const _activeStyleVariant = _styleVariantMap[variant];

  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      {showRelatedCountries ? (
        <Link
          block={"inline"}
          button={false}
          className={`link-block-7 ${_activeStyleVariant}`}
          options={currentPageLink}
        >
          <Image
            alt={""}
            className={`image-201 ${_activeStyleVariant}`}
            height={"45"}
            loading={"lazy"}
            src={block12FlagImg}
            width={"45"}
          />
          <Block
            className={`destination-label-wrap ${_activeStyleVariant}`}
            tag={"div"}
          >
            <Block
              className={`more-destinations-label is-base ${_activeStyleVariant}`}
              tag={"div"}
            >
              {linkTextOne}
            </Block>
            <Block
              className={`more-destinations-label parent ${_activeStyleVariant}`}
              tag={"div"}
            >
              {originCountryName}
            </Block>
            <Block
              className={`more-destinations-label parent ${_activeStyleVariant}`}
              tag={"div"}
            >
              {linkTextThree}
            </Block>
            <Block
              className={`more-destinations-label is-base ${_activeStyleVariant}`}
              tag={"div"}
            >
              {destinationCountryName}
            </Block>
          </Block>
          <HtmlEmbed
            content={
              "<style>\n  .destination-label-wrap::after {\n    content: '';\n    position: absolute;\n    left: 0;\n    right: 0;\n    bottom: 0; /* adjust to sit under the text baseline */\n    height: 2px;\n    background: currentColor;\n  }\n</style>"
            }
          />
        </Link>
      ) : null}
    </div>
  );
}
