/**
 * @generated
 * @file SendBlock1Parent (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import BlockContainer from "./webflow_modules/Layout/components/BlockContainer";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";
import RichText from "./webflow_modules/Basic/components/RichText";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link SendBlock1Parent}
 */
export type SendBlock1ParentProps = {
  block1Body?: React.ReactNode;
  block1Heading?: React.ReactNode;
  image1?: string;
  image2?: string;
  link?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  originCountryCountryFlag?: string;
};

/**
 * SendBlock1Parent
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function SendBlock1Parent({
  block1Body = "",
  block1Heading = "Heading",
  image1 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6743c644ed2b87649db4800b_arrow%20right.svg",
  image2 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a46c5395fd912579c0e9d92_dynamic-image.avif",

  link = {
    href: "#6aa9f74c-70a3-c4b5-fbd3-2cdf5a676743",
  },

  originCountryCountryFlag = "",
}: SendBlock1ParentProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"new-section _w-padding"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <BlockContainer
          className={"new-section-container-9"}
          grid={{
            type: "container",
          }}
          tag={"div"}
        >
          <Block className={"prog-block-one corridor"} tag={"div"}>
            <Block className={"prog-heading-wrapper"} tag={"div"}>
              <Heading className={"new-section-heading is-50"} tag={"h2"}>
                {block1Heading}
              </Heading>
              <Block className={"prog-flag-wrapper"} tag={"div"}>
                <Image
                  alt={""}
                  className={"prog-flag"}
                  height={"auto"}
                  loading={"lazy"}
                  src={originCountryCountryFlag}
                  width={"auto"}
                />
                <Link
                  block={"inline"}
                  button={false}
                  className={"prog-send-wrapper"}
                  options={link}
                >
                  <Image
                    alt={""}
                    className={"prog-send-arow"}
                    height={"auto"}
                    loading={"lazy"}
                    src={image1}
                    width={"auto"}
                  />
                </Link>
              </Block>
              <Image
                alt={""}
                className={"image-205"}
                height={"494"}
                loading={"lazy"}
                src={image2}
                width={"400"}
              />
            </Block>
            <RichText className={"new-subheading is-align-left"} tag={"div"}>
              {block1Body}
            </RichText>
          </Block>
        </BlockContainer>
      </Section>
    </div>
  );
}
