/**
 * @generated
 * @file SendHero (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import BlockContainer from "./webflow_modules/Layout/components/BlockContainer";
import Heading from "./webflow_modules/Basic/components/Heading";
import HtmlEmbed from "./webflow_modules/Embed/components/HtmlEmbed";
import Image from "./webflow_modules/Basic/components/Image";
import Link from "./webflow_modules/Basic/components/Link";
import Section from "./webflow_modules/Layout/components/Section";
import { Button } from "./ds/Button";

/**
 * Props for {@link SendHero}
 */
export type SendHeroProps = {
  bottomFlagImg?: string;
  breadcrumbOneLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  breadcrumbOneText?: React.ReactNode;
  breadcrumbThreeLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  breadcrumbThreeText?: React.ReactNode;
  breadcrumbTwo?: React.ReactNode;
  buttonLinkTo?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  buttonPrimaryBtnText?: React.ReactNode;
  buttonVariant?: "Primary" | "secondary" | "tertiary" | "stylized";
  chevronDown?: string;
  chevronDown1?: string;
  chevronDown2?: string;
  destinationShortcode?: React.ReactNode;
  heroHeading?: React.ReactNode;
  heroSubheading?: React.ReactNode;
  homeLink?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  homeLinkText?: React.ReactNode;
  originCountryShortcode?: React.ReactNode;
  vector?: string;
  widgetSlot?: React.ReactNode;
};

/**
 * SendHero
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function SendHero({
  bottomFlagImg = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a4e2a9d1bc1e3ae02b4d6df_prog-flags-hero.svg",

  breadcrumbOneLink = {
    href: "#",
  },

  breadcrumbOneText = "SWIZTERLAND",

  breadcrumbThreeLink = {
    href: "/money-transfer",
  },

  breadcrumbThreeText = "MONEY TRANSFER",
  breadcrumbTwo = "Send Money from Switzerland to Finland",

  buttonLinkTo = {
    href: "https://app.grey.co/auth/register",
  },

  buttonPrimaryBtnText = "Send Money to Finland",
  buttonVariant = "Primary",
  chevronDown = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/63754bf26e3ec367bc343968_drop-arrow.svg",
  chevronDown1 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/63754bf26e3ec367bc343968_drop-arrow.svg",
  chevronDown2 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/63754bf26e3ec367bc343968_drop-arrow.svg",
  destinationShortcode = "EUR",
  heroHeading = "Send Money to Finland from Switzerland",
  heroSubheading = "Send EUR to OP Financial and other banks in Finland. SEPA delivery in minutes. Rate and fee shown before you confirm.",

  homeLink = {
    href: "/",
  },

  homeLinkText = "HOME",
  originCountryShortcode = "US",
  vector = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6563d397fe1528274b629ba3_bg%20vector.svg",
  widgetSlot,
}: SendHeroProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"prog-hero"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <BlockContainer
          className={"prog-hero-container"}
          grid={{
            type: "container",
          }}
          tag={"div"}
        >
          <Block className={"prog-breadcrumb-wrapper"} tag={"div"}>
            <Link
              button={false}
              className={"prog-breadcrumb"}
              options={homeLink}
            >
              {homeLinkText}
            </Link>
            <Image
              alt={""}
              className={"image-210"}
              height={"auto"}
              loading={"lazy"}
              src={chevronDown1}
              width={"auto"}
            />
            <Link
              button={false}
              className={"prog-breadcrumb"}
              options={breadcrumbThreeLink}
            >
              {breadcrumbThreeText}
            </Link>
            <Image
              alt={""}
              className={"image-210"}
              height={"auto"}
              loading={"lazy"}
              src={chevronDown2}
              width={"auto"}
            />
            <Link
              button={false}
              className={"prog-breadcrumb"}
              options={breadcrumbOneLink}
            >
              {breadcrumbOneText}
            </Link>
            <Image
              alt={""}
              className={"image-210"}
              height={"auto"}
              loading={"lazy"}
              src={chevronDown}
              width={"auto"}
            />
            <Block className={"prog-breadcrumb"} tag={"div"}>
              {breadcrumbTwo}
            </Block>
          </Block>
          <Block className={"prog-hero-content"} tag={"div"}>
            <Block className={"prog-content_block"} tag={"div"}>
              <Block className={"prog-hero-copy"} tag={"div"}>
                <Heading
                  className={"new-hero-heading is-align-left"}
                  tag={"h1"}
                >
                  {heroHeading}
                </Heading>
                <Block
                  className={
                    "new-subheading is-align-left is-100 is-text-light"
                  }
                  tag={"div"}
                >
                  {heroSubheading}
                </Block>
                <Block className={"hidden-country"} tag={"div"}>
                  {originCountryShortcode}
                </Block>
                <Block className={"hidden-country"} tag={"div"}>
                  {destinationShortcode}
                </Block>
                <Block className={"hidden-link"} tag={"div"}>
                  {"Text Link"}
                </Block>
                <Block className={"hidden-link"} tag={"div"}>
                  {"Text Link"}
                </Block>
              </Block>
              <Button
                label={buttonPrimaryBtnText}
                linkTo={buttonLinkTo}
                variant={buttonVariant}
              />
            </Block>
            {widgetSlot}
          </Block>
        </BlockContainer>
        <Image
          alt={""}
          className={"prog-hero-image"}
          height={"284"}
          loading={"lazy"}
          src={bottomFlagImg}
          width={"1462"}
        />
      </Section>
    </div>
  );
}
