/**
 * @generated
 * @file SendBlock10 (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import BlockContainer from "./webflow_modules/Layout/components/BlockContainer";
import Heading from "./webflow_modules/Basic/components/Heading";
import HtmlEmbed from "./webflow_modules/Embed/components/HtmlEmbed";
import Image from "./webflow_modules/Basic/components/Image";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import Section from "./webflow_modules/Layout/components/Section";
import { Button } from "./ds/Button";

/**
 * Props for {@link SendBlock10}
 */
export type SendBlock10Props = {
  block10Body?: React.ReactNode;
  block10GridItem1Body?: React.ReactNode;
  block10GridItem1Heading?: React.ReactNode;
  block10GridItem2Body?: React.ReactNode;
  block10GridItem2Heading?: React.ReactNode;
  block10GridItem3Body?: React.ReactNode;
  block10GridItem3Heading?: React.ReactNode;
  block10GridItem4Body?: React.ReactNode;
  block10GridItem4Heading?: React.ReactNode;
  block10Heading?: React.ReactNode;
  block10PrimaryCta?: React.ReactNode;
  buttonLinkTo?: {
    href: string;
    preload?: "prerender" | "prefetch" | "none";
    target?: "_self" | "_blank";
  };
  buttonVariant?: "Primary" | "secondary" | "tertiary" | "stylized";
  image?: string;
};

/**
 * SendBlock10
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function SendBlock10({
  block10Body = "This is some text inside of a div block.",
  block10GridItem1Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.",
  block10GridItem1Heading = "Heading",
  block10GridItem2Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.",
  block10GridItem2Heading = "Heading",
  block10GridItem3Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.",
  block10GridItem3Heading = "Heading",
  block10GridItem4Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.",
  block10GridItem4Heading = "Heading",
  block10Heading = "Heading",
  block10PrimaryCta = "Primary Button",

  buttonLinkTo = {
    href: "https://app.grey.co/auth/register",
  },

  buttonVariant = "Primary",
  image = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6563d397fe1528274b629ba9_icon%20background.svg",
}: SendBlock10Props) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"new-section-global"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <Image
          alt={"Grey foreign bank account in Brazil."}
          className={"section-motif none"}
          height={"auto"}
          loading={"lazy"}
          src={image}
          width={"auto"}
        />
        <BlockContainer
          className={"new-section-container"}
          grid={{
            type: "container",
          }}
          tag={"div"}
        >
          <Block className={"va-borderless-wrapper"} tag={"div"}>
            <Heading
              className={"new-section-heading_ii is-text-light"}
              tag={"h2"}
            >
              {block10Heading}
            </Heading>
            <Block className={"prog-block_10-grid"} tag={"div"}>
              <Block className={"block_10-grid_item"} tag={"div"}>
                <Block className={"feature-card-copy"} tag={"div"}>
                  <Heading className={"block_10-heading"} tag={"h4"}>
                    {block10GridItem1Heading}
                  </Heading>
                  <Paragraph className={"block_10-body"}>
                    {block10GridItem1Body}
                  </Paragraph>
                </Block>
              </Block>
              <Block className={"block_10-grid_item"} tag={"div"}>
                <Block className={"feature-card-copy"} tag={"div"}>
                  <Heading className={"block_10-heading"} tag={"h4"}>
                    {block10GridItem2Heading}
                  </Heading>
                  <Paragraph className={"block_10-body"}>
                    {block10GridItem2Body}
                  </Paragraph>
                </Block>
              </Block>
              <Block className={"block_10-grid_item"} tag={"div"}>
                <Block className={"feature-card-copy"} tag={"div"}>
                  <Heading className={"block_10-heading"} tag={"h4"}>
                    {block10GridItem3Heading}
                  </Heading>
                  <Paragraph className={"block_10-body"}>
                    {block10GridItem3Body}
                  </Paragraph>
                </Block>
              </Block>
              <Block className={"block_10-grid_item"} tag={"div"}>
                <Block className={"feature-card-copy"} tag={"div"}>
                  <Heading className={"block_10-heading"} tag={"h4"}>
                    {block10GridItem4Heading}
                  </Heading>
                  <Paragraph className={"block_10-body"}>
                    {block10GridItem4Body}
                  </Paragraph>
                </Block>
              </Block>
            </Block>
            <Block className={"new-subheading is-text-light"} tag={"div"}>
              {block10Body}
            </Block>
            <Button
              label={block10PrimaryCta}
              linkTo={buttonLinkTo}
              variant={buttonVariant}
            />
          </Block>
        </BlockContainer>
      </Section>
    </div>
  );
}
