/**
 * @generated
 * @file SendBlock11Parent (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import BlockContainer from "./webflow_modules/Layout/components/BlockContainer";
import Heading from "./webflow_modules/Basic/components/Heading";
import HtmlEmbed from "./webflow_modules/Embed/components/HtmlEmbed";
import Image from "./webflow_modules/Basic/components/Image";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link SendBlock11Parent}
 */
export type SendBlock11ParentProps = {
  block11GridItem1Body?: React.ReactNode;
  block11GridItem1Heading?: React.ReactNode;
  block11GridItem2Body?: React.ReactNode;
  block11GridItem2Heading?: React.ReactNode;
  block11GridItem3Body?: React.ReactNode;
  block11GridItem3Heading?: React.ReactNode;
  block11GridItem4Body?: React.ReactNode;
  block11GridItem4Heading?: React.ReactNode;
  block11Heading?: React.ReactNode;
  image?: string;
};

/**
 * SendBlock11Parent
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function SendBlock11Parent({
  block11GridItem1Body = "This is some text inside of a div block.",
  block11GridItem1Heading = "This is some text inside of a div block.",
  block11GridItem2Body = "This is some text inside of a div block.",
  block11GridItem2Heading = "This is some text inside of a div block.",
  block11GridItem3Body = "This is some text inside of a div block.",
  block11GridItem3Heading = "This is some text inside of a div block.",
  block11GridItem4Body = "This is some text inside of a div block.",
  block11GridItem4Heading = "This is some text inside of a div block.",
  block11Heading = "Heading",
  image = "",
}: SendBlock11ParentProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"new-section _w-padding"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <BlockContainer
          className={"new-section-container"}
          grid={{
            type: "container",
          }}
          tag={"div"}
        >
          <Block className={"section-heading-wrapper"} tag={"div"}>
            <Heading
              className={"new-section-heading_ii is-align-left"}
              tag={"h2"}
            >
              {block11Heading}
            </Heading>
            <Image
              alt={""}
              className={"grey-badge"}
              height={"auto"}
              loading={"lazy"}
              src={image}
              width={"auto"}
            />
          </Block>
          <Block className={"div-block-300"} tag={"div"}>
            <Block
              className={" prog-bw-int"}
              id={"w-node-_4ef1c8d0-0923-eba7-49b8-3805b3ac0115-b3ac010e"}
              tag={"div"}
            >
              <Block className={"whyinvoiceimage _02"} tag={"div"} />
              <Block className={" invoiceperktitle dark"} tag={"div"}>
                {block11GridItem1Heading}
              </Block>
              <Block className={" prog-hc-body"} tag={"div"}>
                {block11GridItem1Body}
              </Block>
            </Block>
            <Block
              className={" prog-bw-int"}
              id={"w-node-_4ef1c8d0-0923-eba7-49b8-3805b3ac0119-b3ac010e"}
              tag={"div"}
            >
              <Block className={"whyinvoiceimage _02"} tag={"div"} />
              <Block className={" invoiceperktitle dark"} tag={"div"}>
                {block11GridItem2Heading}
              </Block>
              <Block className={" prog-hc-body"} tag={"div"}>
                {block11GridItem2Body}
              </Block>
            </Block>
            <Block
              className={" prog-bw-int"}
              id={"w-node-_4ef1c8d0-0923-eba7-49b8-3805b3ac011d-b3ac010e"}
              tag={"div"}
            >
              <Block className={"whyinvoiceimage _02"} tag={"div"} />
              <Block className={" invoiceperktitle dark"} tag={"div"}>
                {block11GridItem3Heading}
              </Block>
              <Block className={" prog-hc-body"} tag={"div"}>
                {block11GridItem3Body}
              </Block>
            </Block>
            <Block
              className={" prog-bw-int"}
              id={"w-node-_4ef1c8d0-0923-eba7-49b8-3805b3ac0121-b3ac010e"}
              tag={"div"}
            >
              <Block className={"whyinvoiceimage _02"} tag={"div"} />
              <Block className={" invoiceperktitle dark"} tag={"div"}>
                {block11GridItem4Heading}
              </Block>
              <Block className={" prog-hc-body"} tag={"div"}>
                {block11GridItem4Body}
              </Block>
            </Block>
          </Block>
        </BlockContainer>
      </Section>
    </div>
  );
}
