/**
 * @generated
 * @file SendFaq (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import BlockContainer from "./webflow_modules/Layout/components/BlockContainer";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link SendFaq}
 */
export type SendFaqProps = {
  bbFaqSlot?: React.ReactNode;
  image?: string;
  title?: React.ReactNode;
};

/**
 * SendFaq
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function SendFaq({
  bbFaqSlot,
  image = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a3ce4299a4672491dc77654_faq-blue.avif",
  title = "FAQs",
}: SendFaqProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"new-section _w-padding faq"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <BlockContainer
          className={"bb-section-container"}
          grid={{
            type: "container",
          }}
          tag={"div"}
        >
          <Block className={"bb-faq-wrapper"} tag={"div"}>
            <Block className={"new-faq-heading"} tag={"div"}>
              <Image
                alt={""}
                className={"faq-image"}
                height={"Auto"}
                loading={"lazy"}
                src={image}
                width={"Auto"}
              />
              <Heading className={"new-section-heading"} tag={"h2"}>
                {title}
              </Heading>
            </Block>
            <Block className={"bb-faq-wrap"} tag={"div"}>
              {bbFaqSlot}
            </Block>
          </Block>
        </BlockContainer>
      </Section>
    </div>
  );
}
