/**
 * @generated
 * @file SendBlock8 (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import BlockContainer from "./webflow_modules/Layout/components/BlockContainer";
import Heading from "./webflow_modules/Basic/components/Heading";
import HtmlEmbed from "./webflow_modules/Embed/components/HtmlEmbed";
import Image from "./webflow_modules/Basic/components/Image";
import Paragraph from "./webflow_modules/Basic/components/Paragraph";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link SendBlock8}
 */
export type SendBlock8Props = {
  block8Body?: React.ReactNode;
  block8GridItem1Body?: React.ReactNode;
  block8GridItem1Heading?: React.ReactNode;
  block8GridItem2Body?: React.ReactNode;
  block8GridItem2Heading?: React.ReactNode;
  block8GridItem3Body?: React.ReactNode;
  block8GridItem3Heading?: React.ReactNode;
  block8Heading?: React.ReactNode;
  image1?: string;
  image2?: string;
  image3?: string;
};

/**
 * SendBlock8
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function SendBlock8({
  block8Body = "This is some text inside of a div block.",
  block8GridItem1Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.",
  block8GridItem1Heading = "Heading",
  block8GridItem2Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.",
  block8GridItem2Heading = "Heading",
  block8GridItem3Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.",
  block8GridItem3Heading = "Heading",
  block8Heading = "Heading",
  image1 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a51172cb36b87597ff813a8_bt.png",
  image2 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a51172c8659d14550ffe4f2_sp.png",
  image3 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a51172b13f8545e2c3e49fc_gt.png",
}: SendBlock8Props) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"new-section _w-padding blue"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <BlockContainer
          className={"new-section-container-9"}
          grid={{
            type: "container",
          }}
          tag={"div"}
        >
          <Block
            className={"section-heading-wrapper flex-down center"}
            tag={"div"}
          >
            <Heading className={"new-section-heading"} tag={"h2"}>
              {block8Heading}
            </Heading>
            <Block className={"new-subheading"} tag={"div"}>
              {block8Body}
            </Block>
            <Block className={"content-spacer"} tag={"div"} />
          </Block>
          <Block className={"gvcgrid _3-col"} tag={"div"}>
            <Block
              className={"gvcitemwrapper"}
              id={"w-node-_6b2ffb19-439f-0d00-014e-3948628c15ce-628c15c6"}
              tag={"div"}
            >
              <Block className={"gvcimageframe is-out"} tag={"div"}>
                <Block className={"gvcimageframe is-in bg-blend"} tag={"div"}>
                  <Image
                    alt={""}
                    className={"gvcimage"}
                    height={"244"}
                    loading={"lazy"}
                    src={image1}
                    width={"355"}
                  />
                </Block>
              </Block>
              <Block className={"gvccopy"} tag={"div"}>
                <Heading className={"gvcheading subheading"} tag={"h3"}>
                  {block8GridItem1Heading}
                </Heading>
                <Paragraph className={"gvcbody sub"}>
                  {block8GridItem1Body}
                </Paragraph>
              </Block>
            </Block>
            <Block
              className={"gvcitemwrapper"}
              id={"w-node-_6b2ffb19-439f-0d00-014e-3948628c15d5-628c15c6"}
              tag={"div"}
            >
              <Block className={"gvcimageframe is-out"} tag={"div"}>
                <Block className={"gvcimageframe is-in"} tag={"div"}>
                  <Image
                    alt={""}
                    className={"gvcimage"}
                    height={"244"}
                    loading={"lazy"}
                    src={image2}
                    width={"355"}
                  />
                </Block>
              </Block>
              <Block className={"gvccopy"} tag={"div"}>
                <Heading className={"gvcheading subheading"} tag={"h3"}>
                  {block8GridItem2Heading}
                </Heading>
                <Paragraph className={"gvcbody sub"}>
                  {block8GridItem2Body}
                </Paragraph>
              </Block>
            </Block>
            <Block
              className={"gvcitemwrapper"}
              id={"w-node-_6b2ffb19-439f-0d00-014e-3948628c15dc-628c15c6"}
              tag={"div"}
            >
              <Block className={"gvcimageframe is-out"} tag={"div"}>
                <Block className={"gvcimageframe is-in"} tag={"div"}>
                  <Image
                    alt={""}
                    className={"gvcimage"}
                    height={"244"}
                    loading={"lazy"}
                    src={image3}
                    width={"355"}
                  />
                </Block>
              </Block>
              <Block className={"gvccopy"} tag={"div"}>
                <Heading className={"gvcheading subheading"} tag={"h3"}>
                  {block8GridItem3Heading}
                </Heading>
                <Paragraph className={"gvcbody sub"}>
                  {block8GridItem3Body}
                </Paragraph>
              </Block>
            </Block>
          </Block>
        </BlockContainer>
      </Section>
    </div>
  );
}
