/**
 * @generated
 * @file SendBlock1 (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import BlockContainer from "./webflow_modules/Layout/components/BlockContainer";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import RichText from "./webflow_modules/Basic/components/RichText";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link SendBlock1}
 */
export type SendBlock1Props = {
  block1Body?: React.ReactNode;
  block1Heading?: React.ReactNode;
  destinationCountryCountryFlag?: string;
  originCountryCountryFlag?: string;
};

/**
 * SendBlock1
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function SendBlock1({
  block1Body = "",
  block1Heading = "Heading",
  destinationCountryCountryFlag = "",
  originCountryCountryFlag = "",
}: SendBlock1Props) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"new-section _w-padding"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <BlockContainer
          className={"new-section-container-9"}
          grid={{
            type: "container",
          }}
          tag={"div"}
        >
          <Block className={"prog-block-one corridor"} tag={"div"}>
            <Block className={"prog-heading-wrapper"} tag={"div"}>
              <Block className={"prog-flag-wrapper"} tag={"div"}>
                <Image
                  alt={""}
                  className={"prog-flag"}
                  height={"auto"}
                  loading={"lazy"}
                  src={originCountryCountryFlag}
                  width={"auto"}
                />
                <Image
                  alt={""}
                  className={"prog-flag"}
                  height={"auto"}
                  loading={"lazy"}
                  src={destinationCountryCountryFlag}
                  width={"auto"}
                />
              </Block>
              <Heading className={"new-section-heading is-50"} tag={"h2"}>
                {block1Heading}
              </Heading>
            </Block>
            <RichText className={"new-subheading is-align-left"} tag={"div"}>
              {block1Body}
            </RichText>
          </Block>
        </BlockContainer>
      </Section>
    </div>
  );
}
