/**
 * @generated
 * @file SendBlock4 (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import BlockContainer from "./webflow_modules/Layout/components/BlockContainer";
import Heading from "./webflow_modules/Basic/components/Heading";
import HtmlEmbed from "./webflow_modules/Embed/components/HtmlEmbed";
import Image from "./webflow_modules/Basic/components/Image";
import RichText from "./webflow_modules/Basic/components/RichText";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link SendBlock4}
 */
export type SendBlock4Props = {
  block4Body?: React.ReactNode;
  block4Heading?: React.ReactNode;
  image1?: string;
  image2?: string;
};

/**
 * SendBlock4
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function SendBlock4({
  block4Body = "",
  block4Heading = "Heading",
  image1 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/67f3f13267934611287cde72_Heart.avif",
  image2 = "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/69fabcf48ef1d300f4975fdc_Convert_Blue.avif",
}: SendBlock4Props) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"new-section _w-padding blue-10"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <BlockContainer
          className={"new-section-container blue-11"}
          grid={{
            type: "container",
          }}
          tag={"div"}
        >
          <Block className={"prog-exchange-section"} tag={"div"}>
            <Block className={"prog-exchange-content"} tag={"div"}>
              <Heading className={"new-section-heading"} tag={"h2"}>
                {block4Heading}
              </Heading>
              <Image
                alt={""}
                className={"csr_icon blue-16"}
                height={"Auto"}
                loading={"lazy"}
                src={image1}
                width={"323"}
              />
              <RichText
                className={"new-subheading is-align-left is-100"}
                tag={"div"}
              >
                {block4Body}
              </RichText>
            </Block>
            <Image
              alt={""}
              className={"prog-exchange-image"}
              height={"936"}
              loading={"lazy"}
              src={image2}
              width={"935"}
            />
          </Block>
        </BlockContainer>
      </Section>
    </div>
  );
}
