/**
 * @generated
 * @file SendBlock13Parent (generated by DevLink)
 *
 * This file is generated by DevLink from a Webflow component. Manual edits are discouraged.
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
"use client";

import { DEVLINK_SCOPE_CLASS } from "./devlinkScope";
import Block from "./webflow_modules/Basic/components/Block";
import BlockContainer from "./webflow_modules/Layout/components/BlockContainer";
import Heading from "./webflow_modules/Basic/components/Heading";
import Image from "./webflow_modules/Basic/components/Image";
import Section from "./webflow_modules/Layout/components/Section";

/**
 * Props for {@link SendBlock13Parent}
 */
export type SendBlock13ParentProps = {
  block13Heading?: React.ReactNode;
  showHeading?: boolean;
};

/**
 * SendBlock13Parent
 *
 * @see {@link https://grey-lp.design.webflow.com | Source site in Webflow}
 */
export function SendBlock13Parent({
  block13Heading = "Heading",
  showHeading = true,
}: SendBlock13ParentProps) {
  return (
    <div
      className={DEVLINK_SCOPE_CLASS}
      style={{
        display: "contents",
      }}
    >
      <Section
        className={"new-section _w-padding"}
        grid={{
          type: "section",
        }}
        tag={"section"}
      >
        <BlockContainer
          className={"new-section-container"}
          grid={{
            type: "container",
          }}
          tag={"div"}
        >
          <Block className={"div-block-301"} tag={"div"}>
            <Block className={"div-block-303"} tag={"div"}>
              <Image
                alt={""}
                className={"image-207"}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a51172bd4756251206ea1b9_avatar-01.png"
                }
                width={"auto"}
              />
              <Image
                alt={""}
                className={"image-207"}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a51172ba3cb5d6747718677_avatar-02.png"
                }
                width={"auto"}
              />
              <Image
                alt={""}
                className={"image-207"}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a51172b7ff5a8bc65ffdc61_avatar-03.png"
                }
                width={"auto"}
              />
              <Image
                alt={""}
                className={"image-203"}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a3e9a76c657efe2d8f0c8a7_stamp-wShadow.png"
                }
                width={"auto"}
              />
              <Image
                alt={""}
                className={"image-207"}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a51172b397a5ccc7b4e9fb2_avatar-04.png"
                }
                width={"auto"}
              />
              <Image
                alt={""}
                className={"image-207"}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a51172bcf45682a488d3605_avatar-06.png"
                }
                width={"auto"}
              />
              <Image
                alt={""}
                className={"image-207"}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a51172bbf4a5dcc27ed00d5_avatar-05.png"
                }
                width={"auto"}
              />
            </Block>
            {showHeading ? (
              <Heading className={"new-section-heading_ii"} tag={"h2"}>
                {block13Heading}
              </Heading>
            ) : null}
            <Block className={"div-block-302"} tag={"div"}>
              <Image
                alt={""}
                className={"prog-trust"}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a46ea112973297a114d9648_fincen.avif"
                }
                width={"auto"}
              />
              <Block className={"logo-dot"} tag={"div"} />
              <Image
                alt={""}
                className={"prog-trust"}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a46ea114bcc47062cf31222_YC.avif"
                }
                width={"auto"}
              />
              <Block className={"logo-dot"} tag={"div"} />
              <Image
                alt={""}
                className={"prog-trust"}
                height={"auto"}
                loading={"lazy"}
                src={
                  "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a46ea113a1e27927460f009_Secure.avif"
                }
                width={"auto"}
              />
            </Block>
          </Block>
        </BlockContainer>
        <Image
          alt={""}
          className={"image-206"}
          height={"auto"}
          loading={"lazy"}
          src={
            "https://cdn.prod.website-files.com/6360022338a81bd6fdbb1145/6a46eba5dcf5f3bdef269e0c_prog-bg-blur.png"
          }
          width={"auto"}
        />
      </Section>
    </div>
  );
}
